# Generated by Django 2.1.7 on 2019-04-12 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, upload_to='')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
