# Generated by Django 2.1.7 on 2019-04-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20190413_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='user',
            field=models.IntegerField(default=0),
        ),
    ]
