# Generated by Django 2.1.7 on 2019-04-14 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_messages_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='bot_feedback',
            field=models.IntegerField(default=1),
        ),
    ]
